name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  verificacao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install Pipenv
        run: pip install pipenv
      - name: Pipenv install dependencias
        run: pipenv sync -d
      - name: Install flake8
        run: pipenv install flake8
      - name: Install Codecov
        run: pipenv install codecov
      - name: Run flake8
        run: pipenv run flake8
      - name: Run Pytest e Coverage
        run: |
          pipenv run pytest --cov=.
          - uses: codecov/codecov-action@v
            with:
              token: ${{ secrets.CODECOV_TOKEN }}
    
      
