name: verificação-do-codigo

on:
  pull_request:
    branches:
      - main

jobs:
  verificacao:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install dependências
        run: python -m pip install --upgrade pip
      - run: pip install flake8
      - name: run flake8
        run: flake8
      
